import Foundation

enum ApiaryCatalog {

    // MARK: - 18 Nectar Sources
    static let nectarBlooms: [NectarBloom] = [
        NectarBloom(id: "wild_clover", name: "Wild Clover", startWeek: 4, endWeek: 18, rarity: 1,
                    preferredWeather: [.clear, .lightRain], yieldFactor: 1.20, honeyTypeId: "honey_clover",
                    locationAngle: 22, locationRadius: 0.32,
                    lore: "Lowland clover, the steady backbone of every keeper's year."),
        NectarBloom(id: "mountain_heather", name: "Mountain Heather", startWeek: 18, endWeek: 26, rarity: 4,
                    preferredWeather: [.clear, .mist, .wind], yieldFactor: 0.85, honeyTypeId: "honey_heather",
                    locationAngle: 70, locationRadius: 0.82,
                    lore: "Late slopes where the air is thin and the honey is amber-dark."),
        NectarBloom(id: "linden", name: "Linden", startWeek: 13, endWeek: 17, rarity: 3,
                    preferredWeather: [.clear], yieldFactor: 1.50, honeyTypeId: "honey_linden",
                    locationAngle: 110, locationRadius: 0.45,
                    lore: "Short, explosive bloom near the old monastery grove."),
        NectarBloom(id: "rapeseed", name: "Rapeseed", startWeek: 5, endWeek: 9, rarity: 1,
                    preferredWeather: [.clear, .mist], yieldFactor: 1.65, honeyTypeId: "honey_rapeseed",
                    locationAngle: 150, locationRadius: 0.25,
                    lore: "Sea of yellow blossom in the lower fields; crystallizes fast."),
        NectarBloom(id: "acacia", name: "Acacia", startWeek: 9, endWeek: 13, rarity: 4,
                    preferredWeather: [.clear, .lightRain], yieldFactor: 1.10, honeyTypeId: "honey_acacia",
                    locationAngle: 185, locationRadius: 0.55,
                    lore: "Pale gold, slow to granulate, prized in city pantries."),
        NectarBloom(id: "buckwheat", name: "Buckwheat", startWeek: 16, endWeek: 22, rarity: 3,
                    preferredWeather: [.clear, .lightRain], yieldFactor: 0.95, honeyTypeId: "honey_buckwheat",
                    locationAngle: 215, locationRadius: 0.36,
                    lore: "Robust, near-black honey from the eastern terraces."),
        NectarBloom(id: "sage", name: "Sage", startWeek: 13, endWeek: 19, rarity: 3,
                    preferredWeather: [.clear, .hotDrought], yieldFactor: 1.00, honeyTypeId: "honey_sage",
                    locationAngle: 245, locationRadius: 0.62,
                    lore: "Grey-green slopes overlooking the river."),
        NectarBloom(id: "lavender", name: "Lavender", startWeek: 14, endWeek: 19, rarity: 3,
                    preferredWeather: [.clear, .hotDrought], yieldFactor: 1.05, honeyTypeId: "honey_lavender",
                    locationAngle: 270, locationRadius: 0.38,
                    lore: "The widow's terrace blooms purple every solstice."),
        NectarBloom(id: "sunflower", name: "Sunflower", startWeek: 15, endWeek: 20, rarity: 2,
                    preferredWeather: [.clear, .hotDrought], yieldFactor: 1.35, honeyTypeId: "honey_sunflower",
                    locationAngle: 300, locationRadius: 0.42,
                    lore: "Tall southern fields, bright as the noon sky."),
        NectarBloom(id: "meadow", name: "Wildflower Meadow", startWeek: 6, endWeek: 22, rarity: 1,
                    preferredWeather: [.clear, .lightRain, .mist], yieldFactor: 1.10, honeyTypeId: "honey_wildflower",
                    locationAngle: 335, locationRadius: 0.50,
                    lore: "A patchwork meadow; never the same bouquet twice."),
        NectarBloom(id: "apple", name: "Apple Orchard", startWeek: 3, endWeek: 7, rarity: 2,
                    preferredWeather: [.clear, .lightRain], yieldFactor: 1.05, honeyTypeId: "honey_orchard",
                    locationAngle: 5, locationRadius: 0.45,
                    lore: "Heirloom orchard, blossom mist at dawn."),
        NectarBloom(id: "cherry", name: "Cherry Bloom", startWeek: 2, endWeek: 6, rarity: 2,
                    preferredWeather: [.clear, .mist], yieldFactor: 0.95, honeyTypeId: "honey_cherry",
                    locationAngle: 35, locationRadius: 0.58,
                    lore: "Short, sweet pink bloom on the northern slope."),
        NectarBloom(id: "honeydew", name: "Forest Honeydew", startWeek: 19, endWeek: 26, rarity: 5,
                    preferredWeather: [.clear, .mist, .lightRain], yieldFactor: 0.75, honeyTypeId: "honey_forest",
                    locationAngle: 88, locationRadius: 0.92,
                    lore: "Dark, resinous, gathered from aphid dew in old conifers."),
        NectarBloom(id: "thyme", name: "Wild Thyme", startWeek: 12, endWeek: 18, rarity: 3,
                    preferredWeather: [.clear, .hotDrought, .wind], yieldFactor: 0.90, honeyTypeId: "honey_thyme",
                    locationAngle: 130, locationRadius: 0.72,
                    lore: "Wind-twisted ridge of stone and herb."),
        NectarBloom(id: "eucalyptus", name: "Eucalyptus", startWeek: 8, endWeek: 16, rarity: 4,
                    preferredWeather: [.clear, .wind], yieldFactor: 1.15, honeyTypeId: "honey_eucalyptus",
                    locationAngle: 170, locationRadius: 0.78,
                    lore: "Imported grove down the gorge, smelt of camphor and resin."),
        NectarBloom(id: "manuka", name: "Manuka", startWeek: 11, endWeek: 16, rarity: 5,
                    preferredWeather: [.clear, .lightRain], yieldFactor: 0.55, honeyTypeId: "honey_manuka",
                    locationAngle: 200, locationRadius: 0.85,
                    lore: "Rare grafted shrub from a distant island, medicinal and prized."),
        NectarBloom(id: "borage", name: "Borage", startWeek: 12, endWeek: 18, rarity: 2,
                    preferredWeather: [.clear, .lightRain], yieldFactor: 1.25, honeyTypeId: "honey_borage",
                    locationAngle: 230, locationRadius: 0.30,
                    lore: "Star-blue blossom near the still waters."),
        NectarBloom(id: "goldenrod", name: "Goldenrod", startWeek: 22, endWeek: 28, rarity: 2,
                    preferredWeather: [.clear, .wind], yieldFactor: 1.05, honeyTypeId: "honey_goldenrod",
                    locationAngle: 255, locationRadius: 0.48,
                    lore: "Last gold of autumn before the frosts settle."),
    ]

    // MARK: - 18 Honey Types
    static let honeyTypes: [HoneyType] = [
        HoneyType(id: "honey_clover", name: "Wild Clover", basePrice: 14, tier: 1, color: "#E8C36A",
                  preferredBuyerIds: ["coop", "bakery"],
                  description: "Mild, table-friendly, the universal honey."),
        HoneyType(id: "honey_heather", name: "Mountain Heather", basePrice: 38, tier: 4, color: "#9B5A2C",
                  preferredBuyerIds: ["pharmacist", "court", "foreign"],
                  description: "Thixotropic, bold, jelly-textured."),
        HoneyType(id: "honey_linden", name: "Linden Bloom", basePrice: 28, tier: 3, color: "#D6B14A",
                  preferredBuyerIds: ["cafe", "inn", "apothecary"],
                  description: "Cool minty finish, popular for tea."),
        HoneyType(id: "honey_rapeseed", name: "Rapeseed", basePrice: 11, tier: 1, color: "#F2D060",
                  preferredBuyerIds: ["coop", "bakery", "brewer"],
                  description: "Pale, crystallizes within weeks; baking favorite."),
        HoneyType(id: "honey_acacia", name: "Acacia Gold", basePrice: 32, tier: 3, color: "#EFD993",
                  preferredBuyerIds: ["cafe", "court", "confectioner"],
                  description: "Clearest of all honeys, slow to candy."),
        HoneyType(id: "honey_buckwheat", name: "Black Buckwheat", basePrice: 26, tier: 3, color: "#5C3318",
                  preferredBuyerIds: ["folk", "brewer", "festival"],
                  description: "Molasses-dark, iron-rich, polarizing flavor."),
        HoneyType(id: "honey_sage", name: "Sage Mountain", basePrice: 24, tier: 2, color: "#B59C3F",
                  preferredBuyerIds: ["apothecary", "inn"],
                  description: "Resinous, slow-crystal, herbaceous."),
        HoneyType(id: "honey_lavender", name: "Lavender Field", basePrice: 30, tier: 3, color: "#C4A04C",
                  preferredBuyerIds: ["cafe", "confectioner", "court"],
                  description: "Floral, perfumed, the gardener's favorite."),
        HoneyType(id: "honey_sunflower", name: "Sunflower", basePrice: 13, tier: 1, color: "#EFB933",
                  preferredBuyerIds: ["coop", "bakery"],
                  description: "Bright yellow, crystallizes fine and creamy."),
        HoneyType(id: "honey_wildflower", name: "Wildflower Mosaic", basePrice: 18, tier: 2, color: "#D08C2E",
                  preferredBuyerIds: ["coop", "festival", "inn"],
                  description: "Variable bouquet, signature of the valley."),
        HoneyType(id: "honey_orchard", name: "Orchard Blossom", basePrice: 19, tier: 2, color: "#E8B25A",
                  preferredBuyerIds: ["bakery", "festival"],
                  description: "Light, apple-y, early-season standby."),
        HoneyType(id: "honey_cherry", name: "Cherry Crown", basePrice: 22, tier: 2, color: "#D88444",
                  preferredBuyerIds: ["cafe", "confectioner"],
                  description: "Pink-tinged early honey, almond hint."),
        HoneyType(id: "honey_forest", name: "Forest Honeydew", basePrice: 44, tier: 5, color: "#3E2A14",
                  preferredBuyerIds: ["court", "foreign", "apothecary"],
                  description: "Mineral, malty, prized by serious tasters."),
        HoneyType(id: "honey_thyme", name: "Wild Thyme", basePrice: 29, tier: 3, color: "#B58838",
                  preferredBuyerIds: ["apothecary", "folk", "inn"],
                  description: "Aromatic, slightly medicinal, herb-shop staple."),
        HoneyType(id: "honey_eucalyptus", name: "Eucalyptus Resin", basePrice: 27, tier: 3, color: "#9C7A2A",
                  preferredBuyerIds: ["pharmacist", "apothecary"],
                  description: "Cooling, camphor edge, sold for chest tonics."),
        HoneyType(id: "honey_manuka", name: "Manuka Reserve", basePrice: 88, tier: 5, color: "#6B3E1B",
                  preferredBuyerIds: ["pharmacist", "court", "foreign", "apothecary"],
                  description: "Rare, medicinal grade, the keeper's prize."),
        HoneyType(id: "honey_borage", name: "Star Borage", basePrice: 21, tier: 2, color: "#D8B26A",
                  preferredBuyerIds: ["confectioner", "cafe"],
                  description: "Light, cucumber-fresh, garnish honey."),
        HoneyType(id: "honey_goldenrod", name: "Goldenrod Autumn", basePrice: 16, tier: 2, color: "#D49B3A",
                  preferredBuyerIds: ["coop", "bakery", "inn"],
                  description: "Last harvest of the year, golden and assertive."),
    ]

    // MARK: - 12 Buyer Archetypes
    static let buyers: [Buyer] = [
        Buyer(id: "coop", name: "Valley Cooperative", archetype: "Cooperative",
              preferredHoney: ["honey_clover", "honey_rapeseed", "honey_sunflower", "honey_wildflower"],
              basePriceMult: 0.95, demandMax: 40,
              blurb: "Bulk buyer, fair price, takes anything sound."),
        Buyer(id: "bakery", name: "The Stone Oven Bakery", archetype: "Bakery",
              preferredHoney: ["honey_rapeseed", "honey_sunflower", "honey_orchard", "honey_clover"],
              basePriceMult: 1.05, demandMax: 22,
              blurb: "Pays extra for granulating honeys for breads and rolls."),
        Buyer(id: "pharmacist", name: "Dr. Hain, Pharmacist", archetype: "Pharmacist",
              preferredHoney: ["honey_manuka", "honey_eucalyptus", "honey_heather"],
              basePriceMult: 1.35, demandMax: 12,
              blurb: "Buys medicinal grades for tinctures and salves."),
        Buyer(id: "court", name: "The Margrave's Court", archetype: "Royal Court",
              preferredHoney: ["honey_acacia", "honey_lavender", "honey_manuka", "honey_forest", "honey_heather"],
              basePriceMult: 1.55, demandMax: 8,
              blurb: "Pays handsomely for rare, presentable jars."),
        Buyer(id: "cafe", name: "Mistwood Café Chain", archetype: "Café Chain",
              preferredHoney: ["honey_linden", "honey_lavender", "honey_acacia", "honey_borage"],
              basePriceMult: 1.15, demandMax: 18,
              blurb: "Light, perfumed honeys to drizzle on tea."),
        Buyer(id: "folk", name: "Old Mara, Folk Healer", archetype: "Folk Healer",
              preferredHoney: ["honey_buckwheat", "honey_thyme", "honey_sage"],
              basePriceMult: 1.20, demandMax: 10,
              blurb: "Buys dark, mineral honeys for old-country remedies."),
        Buyer(id: "brewer", name: "Hopfen Mead Brewery", archetype: "Brewer",
              preferredHoney: ["honey_buckwheat", "honey_rapeseed", "honey_clover"],
              basePriceMult: 0.90, demandMax: 50,
              blurb: "Bulk for fermentation, prefers volume over varietal."),
        Buyer(id: "confectioner", name: "Bonnard Confectioners", archetype: "Confectioner",
              preferredHoney: ["honey_lavender", "honey_cherry", "honey_acacia", "honey_borage"],
              basePriceMult: 1.30, demandMax: 14,
              blurb: "Pays premium for fragrant honeys for nougats and pastilles."),
        Buyer(id: "apothecary", name: "Iva's Apothecary", archetype: "Apothecary",
              preferredHoney: ["honey_sage", "honey_thyme", "honey_eucalyptus", "honey_forest", "honey_manuka"],
              basePriceMult: 1.40, demandMax: 10,
              blurb: "Discerning herbalist who pays for proven varietals."),
        Buyer(id: "festival", name: "Harvest Festival Stall", archetype: "Festival Stall",
              preferredHoney: ["honey_wildflower", "honey_orchard", "honey_buckwheat", "honey_goldenrod"],
              basePriceMult: 1.05, demandMax: 24,
              blurb: "Seasonal stall, prefers signature local honeys."),
        Buyer(id: "inn", name: "The Standing Stag Inn", archetype: "Mountain Inn",
              preferredHoney: ["honey_linden", "honey_sage", "honey_thyme", "honey_wildflower", "honey_goldenrod"],
              basePriceMult: 1.10, demandMax: 16,
              blurb: "Innkeeper buys steady stock for breakfast tables."),
        Buyer(id: "foreign", name: "Foreign Trader Vesna", archetype: "Foreign Trader",
              preferredHoney: ["honey_manuka", "honey_forest", "honey_heather", "honey_lavender"],
              basePriceMult: 1.50, demandMax: 10,
              blurb: "Arrives twice a season with silver and exotic asks."),
    ]

    // MARK: - 22 Inventory Items
    static let inventoryItems: [InventoryItem] = [
        InventoryItem(id: "empty_frame", name: "Empty Frame", category: "Equipment", price: 6, glyph: "frame",
                      description: "Hung empty so bees can draw fresh comb."),
        InventoryItem(id: "foundation", name: "Wax Foundation", category: "Equipment", price: 4, glyph: "foundation",
                      description: "Embossed wax sheet that guides comb construction."),
        InventoryItem(id: "smoker", name: "Beekeeper Smoker", category: "Tool", price: 18, glyph: "smoker",
                      description: "Calms bees with cool smoke before inspection."),
        InventoryItem(id: "tool", name: "Hive Tool", category: "Tool", price: 9, glyph: "tool",
                      description: "Pry bars frames sealed by propolis."),
        InventoryItem(id: "excluder", name: "Queen Excluder", category: "Equipment", price: 12, glyph: "excluder",
                      description: "Keeps the queen off honey supers."),
        InventoryItem(id: "suit", name: "Bee Suit", category: "Apparel", price: 30, glyph: "suit",
                      description: "Reduces stings during difficult inspections."),
        InventoryItem(id: "super", name: "Honey Super", category: "Equipment", price: 22, glyph: "super",
                      description: "Adds an extra box for surplus honey."),
        InventoryItem(id: "queen_cell", name: "Grafted Queen Cell", category: "Livestock", price: 35, glyph: "queenCell",
                      description: "Used to requeen failing colonies."),
        InventoryItem(id: "pollen_sub", name: "Pollen Substitute", category: "Feed", price: 8, glyph: "pollen",
                      description: "Patty fed in dearth to keep brood growing."),
        InventoryItem(id: "sugar", name: "Sugar Syrup (kg)", category: "Feed", price: 3, glyph: "syrup",
                      description: "Emergency feed in winter or pre-harvest gaps."),
        InventoryItem(id: "antibiotic", name: "Antibiotic Powder", category: "Medicine", price: 20, glyph: "medicine",
                      description: "Treats foulbrood and nosema."),
        InventoryItem(id: "mite_strip", name: "Mite Strip", category: "Medicine", price: 14, glyph: "medicine",
                      description: "Slow-release strip that knocks down varroa."),
        InventoryItem(id: "hornet_trap", name: "Hornet Trap", category: "Defense", price: 11, glyph: "trap",
                      description: "Lures and contains attacking hornets."),
        InventoryItem(id: "fire_cover", name: "Fire-Resistant Cover", category: "Defense", price: 28, glyph: "cover",
                      description: "Saves a hive from a wildfire roll."),
        InventoryItem(id: "hive_scale", name: "Hive Scale", category: "Tool", price: 26, glyph: "scale",
                      description: "Tracks honey flow weight for sharper harvests."),
        InventoryItem(id: "refractometer", name: "Refractometer", category: "Tool", price: 32, glyph: "refractometer",
                      description: "Measures moisture so honey doesn't ferment in the jar."),
        InventoryItem(id: "extractor", name: "Hand Extractor", category: "Tool", price: 64, glyph: "extractor",
                      description: "Spins frames to free honey without crushing comb."),
        InventoryItem(id: "tank", name: "Settling Tank", category: "Tool", price: 38, glyph: "tank",
                      description: "Allows wax and bubbles to rise before jarring."),
        InventoryItem(id: "label", name: "Paper Label", category: "Packaging", price: 1, glyph: "label",
                      description: "Marks varietal and year on each jar."),
        InventoryItem(id: "jar", name: "Glass Jar", category: "Packaging", price: 2, glyph: "jar",
                      description: "Standard 500g jar; one per saleable unit."),
        InventoryItem(id: "marker", name: "Queen Marker Pen", category: "Tool", price: 7, glyph: "tool",
                      description: "Paints a year-color dot on the queen's thorax."),
        InventoryItem(id: "winter_wrap", name: "Winter Wrap", category: "Defense", price: 16, glyph: "cover",
                      description: "Insulates a hive against the deepest cold."),
    ]

    // MARK: - 20 Upgrades
    static let upgrades: [Upgrade] = [
        Upgrade(id: "slot_9", name: "Clearing: 9th Slot", cost: 220, requiredPrestige: 0,
                description: "Clears scrub for a ninth hive stand.", unlockTag: "slot+1"),
        Upgrade(id: "slot_10", name: "Clearing: 10th Slot", cost: 320, requiredPrestige: 3,
                description: "Tenth hive stand at the orchard edge.", unlockTag: "slot+1"),
        Upgrade(id: "slot_12", name: "Clearing: 12th Slot", cost: 460, requiredPrestige: 6,
                description: "Two more stands on the south slope.", unlockTag: "slot+2"),
        Upgrade(id: "slot_15", name: "Apiary Expansion", cost: 720, requiredPrestige: 10,
                description: "Three additional stands across the meadow.", unlockTag: "slot+3"),
        Upgrade(id: "slot_20", name: "Margrave's Charter", cost: 1200, requiredPrestige: 18,
                description: "Final five stands under royal charter.", unlockTag: "slot+5"),
        Upgrade(id: "better_boxes", name: "Cedar Hive Boxes", cost: 180, requiredPrestige: 1,
                description: "Sturdier boxes reduce disease spread chance.", unlockTag: "disease_resist"),
        Upgrade(id: "fence", name: "Electric Fence", cost: 260, requiredPrestige: 2,
                description: "Halves the chance of bear or theft events.", unlockTag: "predator_guard"),
        Upgrade(id: "smoker_pro", name: "Pro Smoker", cost: 90, requiredPrestige: 1,
                description: "Inspections add +5 temperament after each visit.", unlockTag: "inspection_calm"),
        Upgrade(id: "extractor_pro", name: "Geared Extractor", cost: 380, requiredPrestige: 4,
                description: "+1 jar per harvested frame.", unlockTag: "extract_bonus"),
        Upgrade(id: "extractor_master", name: "Radial Extractor", cost: 720, requiredPrestige: 9,
                description: "+2 jars per harvested frame.", unlockTag: "extract_super_bonus"),
        Upgrade(id: "refract_pro", name: "Calibrated Refractometer", cost: 160, requiredPrestige: 2,
                description: "Reduces spoiled jar chance to near zero.", unlockTag: "no_spoil"),
        Upgrade(id: "queen_station", name: "Queen-Rearing Station", cost: 540, requiredPrestige: 6,
                description: "Produces a queen cell every 4 weeks.", unlockTag: "queen_rearing"),
        Upgrade(id: "observation", name: "Observation Deck", cost: 200, requiredPrestige: 3,
                description: "Catch swarms early; halves swarm losses.", unlockTag: "anti_swarm"),
        Upgrade(id: "scale_sensor", name: "Scale-Hive Sensor", cost: 280, requiredPrestige: 4,
                description: "Shows weekly flow estimates per hive.", unlockTag: "flow_visible"),
        Upgrade(id: "pollen_trap", name: "Pollen Trap", cost: 140, requiredPrestige: 2,
                description: "Collects pollen substitute weekly.", unlockTag: "pollen_gen"),
        Upgrade(id: "hornet_sentinel", name: "Hornet Sentinel", cost: 220, requiredPrestige: 4,
                description: "Auto-deploys traps on hornet events.", unlockTag: "auto_hornet"),
        Upgrade(id: "winter_wrap_set", name: "Winter Wrap Set", cost: 180, requiredPrestige: 3,
                description: "Wraps all hives in winter automatically.", unlockTag: "auto_winter"),
        Upgrade(id: "shrine", name: "Roadside Shrine", cost: 120, requiredPrestige: 5,
                description: "Travellers add +1 prestige per quarter sold.", unlockTag: "prestige_boost"),
        Upgrade(id: "guildmark", name: "Guildmark Permit", cost: 460, requiredPrestige: 7,
                description: "Unlocks the Foreign Trader at all weeks.", unlockTag: "foreign_always"),
        Upgrade(id: "almanac", name: "Beekeeper's Almanac", cost: 100, requiredPrestige: 1,
                description: "Reveals upcoming bloom forecasts.", unlockTag: "bloom_forecast"),
    ]

    // MARK: - 22 Events
    static let events: [ApiaryEvent] = [
        ApiaryEvent(id: "swarm_departing", title: "Swarm in the Air",
                    body: "A strong colony has cast a swarm. You can chase it, accept the loss, or split now.",
                    weight: 14, allowedSeasons: [.spring, .summer],
                    options: [
                        EventOption(label: "Catch the swarm", resultText: "Caught a new mini-colony; population +6000 across hives.",
                                    coinDelta: -10, prestigeDelta: 1, populationDelta: 6000, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Let them go", resultText: "Swarm lost; population reduced.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: -5000, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Pre-emptive split", resultText: "Population stabilized.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: -2000, honeyFramesDelta: 0, diseaseRiskDelta: -0.05, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "queen_failure", title: "A Queen is Faltering",
                    body: "Spotty brood pattern, drone laying. You can requeen or wait.",
                    weight: 10, allowedSeasons: Season.allCases,
                    options: [
                        EventOption(label: "Requeen now", resultText: "Used a queen cell; brood recovered.",
                                    coinDelta: -35, prestigeDelta: 1, populationDelta: 1500, honeyFramesDelta: 0, diseaseRiskDelta: 0,
                                    requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Buy a new queen", resultText: "A travelling breeder sold us a fine queen.",
                                    coinDelta: -55, prestigeDelta: 0, populationDelta: 1500, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Wait and watch", resultText: "Population dropped further.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: -3500, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "robbing", title: "Robbing Attack",
                    body: "Stronger colonies storm a weak hive.", weight: 9, allowedSeasons: [.summer, .autumn],
                    options: [
                        EventOption(label: "Narrow entrances", resultText: "Robbing repelled with minor loss.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: -500, honeyFramesDelta: -1, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Move weak hive aside", resultText: "Saved from robbing entirely.",
                                    coinDelta: 0, prestigeDelta: 1, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Do nothing", resultText: "Weak hive lost most stores.",
                                    coinDelta: 0, prestigeDelta: -1, populationDelta: -1500, honeyFramesDelta: -4, diseaseRiskDelta: 0.05, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "bear", title: "Bear Visit",
                    body: "Footprints around the apiary at dawn.", weight: 6, allowedSeasons: [.spring, .summer, .autumn],
                    options: [
                        EventOption(label: "Set strong fence", resultText: "Bear did not return.",
                                    coinDelta: -25, prestigeDelta: 1, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Wait and hope", resultText: "Bear returned and knocked over a hive.",
                                    coinDelta: 0, prestigeDelta: -1, populationDelta: -8000, honeyFramesDelta: -6, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Move hives uphill", resultText: "Safer, but the move stressed colonies.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: -1000, honeyFramesDelta: 0, diseaseRiskDelta: 0.02, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "arson", title: "Arsonist in the Valley",
                    body: "Smoke on the ridge. You can cover hives or relocate.", weight: 4, allowedSeasons: [.summer, .autumn],
                    options: [
                        EventOption(label: "Deploy fire covers", resultText: "Hives spared from the spark fall.",
                                    coinDelta: 0, prestigeDelta: 2, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0,
                                    requiresItemId: "fire_cover", consumesItemId: "fire_cover"),
                        EventOption(label: "Wet down the area", resultText: "Some hives scorched.",
                                    coinDelta: -20, prestigeDelta: 0, populationDelta: -2000, honeyFramesDelta: -2, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Do nothing", resultText: "Significant losses.",
                                    coinDelta: 0, prestigeDelta: -2, populationDelta: -10000, honeyFramesDelta: -8, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "neighbor", title: "Kind Neighbor",
                    body: "A neighbor brings a surplus of empty frames and asks only a jar.",
                    weight: 12, allowedSeasons: Season.allCases,
                    options: [
                        EventOption(label: "Accept the trade", resultText: "+5 empty frames, -1 jar.",
                                    coinDelta: 0, prestigeDelta: 1, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Pay coin instead", resultText: "+5 empty frames at a fair price.",
                                    coinDelta: -18, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Politely decline", resultText: "Neighbor leaves a little disappointed.",
                                    coinDelta: 0, prestigeDelta: -1, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "honey_show", title: "Honey-Show Invitation",
                    body: "The town honey show is next week. Enter a jar for fame.",
                    weight: 8, allowedSeasons: [.summer, .autumn],
                    options: [
                        EventOption(label: "Enter your finest jar", resultText: "Took third place. Reputation rising.",
                                    coinDelta: 12, prestigeDelta: 3, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Sell at the show", resultText: "Easy direct sale at retail price.",
                                    coinDelta: 35, prestigeDelta: 1, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Skip the show", resultText: "Stayed home and tended the bees.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "cold_spell", title: "Late Cold Spell",
                    body: "An unseasonal cold snap is brewing on the high ridge.",
                    weight: 7, allowedSeasons: [.spring, .autumn],
                    options: [
                        EventOption(label: "Feed sugar immediately", resultText: "Cluster held strong.",
                                    coinDelta: -6, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Wrap with insulation", resultText: "Hives held heat through the snap.",
                                    coinDelta: -10, prestigeDelta: 1, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Ride it out", resultText: "Some brood was chilled.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: -1500, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "wildflower_bloom", title: "Surprise Wildflower Bloom",
                    body: "An unexpected meadow has burst into colour after the rain.",
                    weight: 10, allowedSeasons: [.spring, .summer],
                    options: [
                        EventOption(label: "Move hives closer", resultText: "+3 honey frames across the apiary.",
                                    coinDelta: 0, prestigeDelta: 1, populationDelta: 0, honeyFramesDelta: 3, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Mark on the map", resultText: "+2 honey frames over coming weeks.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 2, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Leave it for nature", resultText: "Nothing changes.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "bandits", title: "Bandit Raid",
                    body: "Stories of bandits stealing jars from outlying apiaries.",
                    weight: 5, allowedSeasons: [.summer, .autumn],
                    options: [
                        EventOption(label: "Hide jars in the cellar", resultText: "Saved the inventory.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Pay protection silver", resultText: "Bandits avoided your apiary.",
                                    coinDelta: -40, prestigeDelta: -1, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Stand watch yourself", resultText: "Lost a single jar before they ran.",
                                    coinDelta: 0, prestigeDelta: 2, populationDelta: 0, honeyFramesDelta: -1, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "hornet", title: "Giant Hornets Sighted",
                    body: "Scouts circling the apiary at dusk.", weight: 8, allowedSeasons: [.summer, .autumn],
                    options: [
                        EventOption(label: "Set hornet traps", resultText: "Sentry hornets eliminated.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0,
                                    requiresItemId: "hornet_trap", consumesItemId: "hornet_trap"),
                        EventOption(label: "Reduce entrance size", resultText: "Some losses but the colony held.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: -1200, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Ignore the scouts", resultText: "A nest forms nearby; large losses.",
                                    coinDelta: 0, prestigeDelta: -1, populationDelta: -6000, honeyFramesDelta: -3, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "varroa_spike", title: "Varroa Spike Detected",
                    body: "A sticky board reveals heavy mite drop.",
                    weight: 12, allowedSeasons: [.summer, .autumn],
                    options: [
                        EventOption(label: "Apply mite strips", resultText: "Mite count knocked back.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: -0.30,
                                    requiresItemId: "mite_strip", consumesItemId: "mite_strip"),
                        EventOption(label: "Sugar dusting", resultText: "Helped a little. Free.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: -0.10, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Wait and see", resultText: "Mites multiplied further.",
                                    coinDelta: 0, prestigeDelta: -1, populationDelta: -1500, honeyFramesDelta: 0, diseaseRiskDelta: 0.20, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "foreign_offer", title: "Foreign Trader's Offer",
                    body: "Vesna offers a rare cutting of mountain shrub for a heavy purse.",
                    weight: 4, allowedSeasons: [.summer, .autumn],
                    options: [
                        EventOption(label: "Buy the cutting", resultText: "Manuka blooms will be more reliable next year.",
                                    coinDelta: -120, prestigeDelta: 3, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Barter with honey", resultText: "Traded twelve jars for the cutting.",
                                    coinDelta: 0, prestigeDelta: 2, populationDelta: 0, honeyFramesDelta: -2, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Decline", resultText: "Vesna pockets the cutting and is gone.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "apprentice", title: "Apprentice at the Gate",
                    body: "A young keeper asks to learn for a season for half wage.",
                    weight: 7, allowedSeasons: [.spring, .summer],
                    options: [
                        EventOption(label: "Take them on", resultText: "Inspections this season are gentler.",
                                    coinDelta: -30, prestigeDelta: 2, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: -0.05, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Trade tutoring for jars", resultText: "Apprentice helps without coin.",
                                    coinDelta: 0, prestigeDelta: 1, populationDelta: 0, honeyFramesDelta: -2, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Send them on", resultText: "You keep your routine intact.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "wild_swarm", title: "Wild Swarm in the Orchard",
                    body: "A feral swarm has clustered in your old apple tree.",
                    weight: 10, allowedSeasons: [.spring, .summer],
                    options: [
                        EventOption(label: "Hive the swarm", resultText: "Caught a wild colony; population +5000.",
                                    coinDelta: 0, prestigeDelta: 1, populationDelta: 5000, honeyFramesDelta: 0, diseaseRiskDelta: 0.05, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Sell the lead to a neighbor", resultText: "Easy silver.",
                                    coinDelta: 25, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Leave them to nature", resultText: "They flew off by evening.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "drought", title: "Drought Warning",
                    body: "The valley well is low and forage is faltering.",
                    weight: 6, allowedSeasons: [.summer],
                    options: [
                        EventOption(label: "Set water troughs", resultText: "Bees fared better; minor cost.",
                                    coinDelta: -8, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Pay for irrigation", resultText: "Improved meadow flow.",
                                    coinDelta: -25, prestigeDelta: 1, populationDelta: 0, honeyFramesDelta: 2, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Ride the dryness", resultText: "Reduced yields.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: -2, diseaseRiskDelta: 0.05, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "festival_call", title: "Festival Stall Wants Stock",
                    body: "The harvest stall asks for any extra jars at fair price.",
                    weight: 10, allowedSeasons: [.autumn],
                    options: [
                        EventOption(label: "Send four jars", resultText: "Quick coin and a good name.",
                                    coinDelta: 70, prestigeDelta: 1, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Send two jars", resultText: "Modest sale.",
                                    coinDelta: 36, prestigeDelta: 1, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Hold stock for buyers", resultText: "Saved jars for better prices.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "rumor", title: "Rumor of Foulbrood",
                    body: "A neighboring apiary is said to be diseased.",
                    weight: 6, allowedSeasons: [.summer, .autumn],
                    options: [
                        EventOption(label: "Quarantine sourced bees", resultText: "Apiary protected.",
                                    coinDelta: 0, prestigeDelta: 1, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: -0.10, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Treat preemptively", resultText: "Used antibiotics as caution.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: -0.20,
                                    requiresItemId: "antibiotic", consumesItemId: "antibiotic"),
                        EventOption(label: "Ignore the rumor", resultText: "Risk has climbed.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0.15, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "windstorm", title: "Heavy Windstorm",
                    body: "A north wind threatens to tip lighter hives.",
                    weight: 6, allowedSeasons: [.spring, .autumn, .winter],
                    options: [
                        EventOption(label: "Strap and weight all hives", resultText: "All hives held.",
                                    coinDelta: -8, prestigeDelta: 1, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Only the weak ones", resultText: "Two hives were tipped but no losses.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: -300, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Trust the stands", resultText: "One hive toppled in the night.",
                                    coinDelta: 0, prestigeDelta: -1, populationDelta: -3000, honeyFramesDelta: -2, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "stolen_jar", title: "A Jar Missing",
                    body: "A passing traveler may have helped themselves.",
                    weight: 4, allowedSeasons: [.summer, .autumn],
                    options: [
                        EventOption(label: "Add a lock to the shed", resultText: "No more visits.",
                                    coinDelta: -10, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Leave a 'free jar' note", resultText: "Goodwill in the village rises.",
                                    coinDelta: 0, prestigeDelta: 2, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Pretend you didn't notice", resultText: "Another jar vanished.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: -1, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "winter_break", title: "Mid-Winter Cluster Check",
                    body: "Stethoscope to the side reveals a faint hum.",
                    weight: 8, allowedSeasons: [.winter],
                    options: [
                        EventOption(label: "Feed fondant", resultText: "Cluster sustained.",
                                    coinDelta: -6, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Add winter wrap", resultText: "Insulated against the coming weeks.",
                                    coinDelta: 0, prestigeDelta: 1, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: -0.05,
                                    requiresItemId: "winter_wrap", consumesItemId: "winter_wrap"),
                        EventOption(label: "Disturb nothing", resultText: "The cluster shifts on its own.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
        ApiaryEvent(id: "wandering_keeper", title: "Wandering Keeper",
                    body: "An elder beekeeper passes through and offers a hint of wisdom.",
                    weight: 8, allowedSeasons: Season.allCases,
                    options: [
                        EventOption(label: "Buy them dinner", resultText: "They share a queen-rearing trick.",
                                    coinDelta: -12, prestigeDelta: 2, populationDelta: 600, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Trade a jar for wisdom", resultText: "They share a foulbrood remedy.",
                                    coinDelta: 0, prestigeDelta: 1, populationDelta: 0, honeyFramesDelta: -1, diseaseRiskDelta: -0.05, requiresItemId: nil, consumesItemId: nil),
                        EventOption(label: "Wish them safe road", resultText: "They go on; the apiary remains the same.",
                                    coinDelta: 0, prestigeDelta: 0, populationDelta: 0, honeyFramesDelta: 0, diseaseRiskDelta: 0, requiresItemId: nil, consumesItemId: nil),
                    ]),
    ]

    // MARK: - 32 Achievements
    static func starterAchievements() -> [Achievement] {
        let items: [(String, String, String)] = [
            ("first_jar", "First Jar", "Sell your very first jar of honey."),
            ("first_harvest", "First Harvest", "Harvest a honey frame from any hive."),
            ("foulbrood_save", "Saved from Foulbrood", "Cure a hive of foulbrood."),
            ("varroa_crusher", "Varroa Crusher", "Defeat heavy varroa with mite strips."),
            ("queen_rearer", "Queen-Rearer", "Successfully requeen a colony."),
            ("hundred_jars", "Hundred Jars", "Sell one hundred jars total."),
            ("survivor_one", "Through the Winter", "Overwinter every hive in one season."),
            ("survivor_three", "Three Winters", "Reach Year 3."),
            ("season_full", "A Full Year", "Complete a full year-cycle."),
            ("clover_master", "Clover Master", "Sell 30 Wild Clover jars."),
            ("heather_master", "Heather Master", "Sell a jar of Mountain Heather."),
            ("linden_master", "Linden Master", "Sell a jar of Linden Bloom."),
            ("rapeseed_master", "Rapeseed Master", "Sell a jar of Rapeseed."),
            ("acacia_master", "Acacia Master", "Sell a jar of Acacia Gold."),
            ("buckwheat_master", "Buckwheat Master", "Sell a jar of Black Buckwheat."),
            ("sage_master", "Sage Master", "Sell a jar of Sage Mountain."),
            ("lavender_master", "Lavender Master", "Sell a jar of Lavender Field."),
            ("sunflower_master", "Sunflower Master", "Sell a jar of Sunflower."),
            ("wildflower_master", "Wildflower Master", "Sell a jar of Wildflower Mosaic."),
            ("orchard_master", "Orchard Master", "Sell a jar of Orchard Blossom."),
            ("cherry_master", "Cherry Master", "Sell a jar of Cherry Crown."),
            ("forest_master", "Forest Master", "Sell a jar of Forest Honeydew."),
            ("thyme_master", "Thyme Master", "Sell a jar of Wild Thyme."),
            ("eucalyptus_master", "Eucalyptus Master", "Sell a jar of Eucalyptus Resin."),
            ("manuka_master", "Manuka Master", "Sell a jar of Manuka Reserve."),
            ("borage_master", "Borage Master", "Sell a jar of Star Borage."),
            ("goldenrod_master", "Goldenrod Master", "Sell a jar of Goldenrod Autumn."),
            ("twelve_buyers", "Open for Business", "Sell to all twelve buyer types."),
            ("prestige_ten", "Reputation: Ten", "Reach 10 prestige."),
            ("prestige_twenty", "Reputation: Twenty", "Reach 20 prestige."),
            ("apiary_grown", "Apiary Grown", "Expand to twelve hive slots."),
            ("apiary_grand", "Grand Apiary", "Expand to twenty hive slots."),
        ]
        return items.map { Achievement(id: $0.0, name: $0.1, description: $0.2, unlockedYear: nil) }
    }

    // MARK: - 30 Quests
    static func starterQuests() -> [Quest] {
        return [
            Quest(id: "q01", name: "Apprentice's Pledge", goal: "Harvest your first honey frame.",
                  reward: "+10 silver, +1 prestige", completed: false, act: 1),
            Quest(id: "q02", name: "First Light", goal: "Sell your first jar at the market.",
                  reward: "+15 silver", completed: false, act: 1),
            Quest(id: "q03", name: "Healthy Apiary", goal: "Keep every hive disease-free for 4 weeks.",
                  reward: "+2 prestige", completed: false, act: 1),
            Quest(id: "q04", name: "Mark the Queens", goal: "Mark a queen in any hive.",
                  reward: "+5 silver", completed: false, act: 1),
            Quest(id: "q05", name: "Patchwork Larder", goal: "Stockpile 10 jars of any honey.",
                  reward: "+20 silver", completed: false, act: 1),
            Quest(id: "q06", name: "Spring's End", goal: "Complete the spring season.",
                  reward: "+1 prestige", completed: false, act: 1),
            Quest(id: "q07", name: "Summer's Edge", goal: "Reach Week 11.",
                  reward: "+1 mite strip", completed: false, act: 1),
            Quest(id: "q08", name: "The First Buyer", goal: "Sell to The Stone Oven Bakery.",
                  reward: "+8 silver", completed: false, act: 1),
            Quest(id: "q09", name: "The Smoker", goal: "Buy a beekeeper smoker.",
                  reward: "+1 prestige", completed: false, act: 1),
            Quest(id: "q10", name: "Modest Stewardship", goal: "Have 8 healthy hives at once.",
                  reward: "+25 silver", completed: false, act: 1),
            Quest(id: "q11", name: "Heir to the Heritage", goal: "Reach Year 2.",
                  reward: "+2 prestige, +30 silver", completed: false, act: 2),
            Quest(id: "q12", name: "Cellar Stocked", goal: "Stockpile 40 jars of any honey.",
                  reward: "+30 silver", completed: false, act: 2),
            Quest(id: "q13", name: "Disease Defeated", goal: "Cure a hive of any disease.",
                  reward: "+2 prestige", completed: false, act: 2),
            Quest(id: "q14", name: "The Court's Eye", goal: "Sell a jar to the Margrave's Court.",
                  reward: "+15 silver", completed: false, act: 2),
            Quest(id: "q15", name: "Mistwood Regular", goal: "Sell five jars to Mistwood Café Chain.",
                  reward: "+20 silver", completed: false, act: 2),
            Quest(id: "q16", name: "Dark Honey", goal: "Sell a jar of Black Buckwheat.",
                  reward: "+12 silver", completed: false, act: 2),
            Quest(id: "q17", name: "Almanac Read", goal: "Buy the Beekeeper's Almanac.",
                  reward: "+1 prestige", completed: false, act: 2),
            Quest(id: "q18", name: "Hardy Stewardship", goal: "Reach Year 3.",
                  reward: "+3 prestige, +50 silver", completed: false, act: 2),
            Quest(id: "q19", name: "Ten Hives", goal: "Expand to ten hive slots.",
                  reward: "+30 silver", completed: false, act: 2),
            Quest(id: "q20", name: "Through the Snow", goal: "Overwinter all hives once.",
                  reward: "+3 prestige", completed: false, act: 2),
            Quest(id: "q21", name: "Old Mara's Trust", goal: "Sell three jars to Old Mara.",
                  reward: "+20 silver", completed: false, act: 3),
            Quest(id: "q22", name: "Apothecary's Favor", goal: "Sell three jars to Iva's Apothecary.",
                  reward: "+20 silver", completed: false, act: 3),
            Quest(id: "q23", name: "The Trader's Caravan", goal: "Sell to Vesna the Foreign Trader.",
                  reward: "+25 silver, +2 prestige", completed: false, act: 3),
            Quest(id: "q24", name: "Mountain Reserve", goal: "Sell a jar of Manuka Reserve.",
                  reward: "+40 silver, +2 prestige", completed: false, act: 3),
            Quest(id: "q25", name: "Forest Reserve", goal: "Sell a jar of Forest Honeydew.",
                  reward: "+25 silver, +1 prestige", completed: false, act: 3),
            Quest(id: "q26", name: "Pillars of the Valley", goal: "Reach 20 prestige.",
                  reward: "+100 silver", completed: false, act: 3),
            Quest(id: "q27", name: "Hundred Jars Sold", goal: "Sell 100 jars total.",
                  reward: "+50 silver, +3 prestige", completed: false, act: 3),
            Quest(id: "q28", name: "Twelve Buyers Won", goal: "Sell to all twelve buyer archetypes.",
                  reward: "+60 silver, +5 prestige", completed: false, act: 3),
            Quest(id: "q29", name: "Heritage Restored", goal: "Reach the maximum twenty hive slots.",
                  reward: "+120 silver, +5 prestige", completed: false, act: 3),
            Quest(id: "q30", name: "Master of the Apiary", goal: "Complete five years.",
                  reward: "Endless prestige", completed: false, act: 3),
        ]
    }

    // MARK: - Starter hives
    static func starterHives() -> [Hive] {
        let names = ["Cedar Stand", "Birch Edge", "Linden Walk", "Sunny Slope", "Old Orchard",
                     "Mossy Hollow", "Stone Wall", "Brookside"]
        let races: [BeeRace] = [.italian, .carniolan, .buckfast, .russian, .caucasian, .italian, .carniolan, .buckfast]
        return zip(names, races).enumerated().map { idx, pair in
            Hive.starter(index: idx, name: pair.0, race: pair.1)
        }
    }

    // MARK: - Lookup helpers
    static func honeyType(id: String) -> HoneyType? { honeyTypes.first { $0.id == id } }
    static func buyer(id: String) -> Buyer? { buyers.first { $0.id == id } }
    static func nectar(id: String) -> NectarBloom? { nectarBlooms.first { $0.id == id } }
    static func item(id: String) -> InventoryItem? { inventoryItems.first { $0.id == id } }
    static func upgrade(id: String) -> Upgrade? { upgrades.first { $0.id == id } }
}
